# Compiler to use.
CXX := g++
# Compiler flags.
CXXFLAGS := -Wall -Wextra -Werror -Wpedantic
# Linker flags.
CXXLFLAGS :=

# Directories to use.
BIN_DIR := bin
OBJ_DIR := obj
INC_DIR := inc
MWE_DIR := mwe

# Minimal working examples.
MWES := $(wildcard $(MWE_DIR)/*.cpp)
# Object files generated by MWES.
OBJS := $(MWES:$(MWE_DIR)/%.cpp=$(OBJ_DIR)/%.o)
# Compiled minimal working examples.
EXES := $(patsubst $(MWE_DIR)/%.cpp,$(BIN_DIR)/%,$(MWES))

##### Public targets.

.PHONY: release debug config clean help _build

release: CXXFLAGS += -O3 -march=native -mtune=native
release: config _build

debug: CXXFLAGS += -Og -ggdb3
debug: config _build

config:
	@echo "Variables:"
	@echo "  CXX       = $(CXX)"
	@echo "  CXXFLAGS  = $(CXXFLAGS)"
	@echo "  CXXLFLAGS = $(CXXLFLAGS)"
	@echo
	@echo "  BIN_DIR = $(BIN_DIR)"
	@echo "  OBJ_DIR = $(OBJ_DIR)"
	@echo "  INC_DIR = $(INC_DIR)"
	@echo "  MWE_DIR = $(MWE_DIR)"
	@echo
	@echo "  MWES = $(MWES)"
	@echo "  OBJS = $(OBJS)"
	@echo "  EXES = $(EXES)"

clean:
	rm -f $(BIN_DIR)/* $(OBJ_DIR)/*.o

help:
	@echo "Available targets:"
	@echo "  release  - Build with maximum optimizations (default)"
	@echo "  debug    - Build with debugging information"
	@echo "  config   - Display the value of variables"
	@echo "  clean    - Remove all generated files"
	@echo "  help     - Display this message"

##### Internal targets.

_build: $(EXES)

$(BIN_DIR)/%: $(MWE_DIR)/%.cpp
	$(CXX) $(CXXFLAGS) $(CXXLFLAGS) -I $(INC_DIR) -c $< -o $@
